### ISSUE TITLE
Daemon crashing on /filter/$blockheight requests

### ISSUE THREAD

**Issue by ottosch** [setavenger/blindbitd#11]
After `./blindbit-cli unlock`, daemon is crashing on `daemon.go, line 54, d.SyncToTip` after calling http://localhost:8000/filter/$blockheight and receiving HTTP 500:
> {"error":"could not get filter from db"}

Crashes with error:
> [ERROR] invalid hash length of 0, want 32

Blindbit-oracle returns that error on client.go:
```
retrieveByBlockHash()
  db.Get(blockHashBytes, nil)
    if err != nil && err.Error() == "leveldb: not found"
```

Happened first time on block 195896 (signet). I deleted all data, restored from mnemonics (set birthheight 100000) and it crashed on block 100001.

**Comment by setavenger** [comment]
I'm having a bad time reproducing this problem. Can you provide both logs for oracle, maybe something helpful is in there.
If you get a leveldb not found it means that there is no data for this block in blindbit-oracle. 
Looking at the block there should be a filter though. Maybe also check whether Oracle is has indexed that block properly.

If none of these options produce anything meaningful we can look at reindexing the chain with oracle.

**Comment by ottosch** [comment]
Sorry for the delay. I deleted all logs and data and synced again.
Restored the wallet with birthheight 1. It crashed on block 8617.

Logs:
[logs.zip](https://github.com/setavenger/blindbitd/files/15395801/logs.zip)

Edit: can send the (signet) seed words if that's helpful too.

**Comment by setavenger** [comment]
The seed won't be necessary :) And I'm not trying to start the practice that I need the seed to resolve bugs. 
The issue lies with Oracle. I'm not sure though why exactly this is happening. There is no filter for this block.
I just ran a quick script and it seems that block 8617 is the first block with tweaks. Are you running Oracle in tweaks-only mode?
blindbitd only requests a filter for a block if it also contains a tweak.
Could you check whether any block has a filter. You can just call the filter endpoint for a couple of blocks. Even if no tweaks exist a filter should be present. 

If no blocks have a filter this would give us a direction.

**Comment by ottosch** [comment]
Apparently yes, I see this on my oracle's blindbit.toml:
```
# optional - will only generate tweaks (still both cut-through and full-index)
# default: 0 set to 1 to activate
tweaks_only = 1
```

I looped with curl, calling `/filters/$block`, from blocks 1 to 8617 and from 195000 to 195896 and they all returned "{"error":"could not get filter from db"}".

Edit: I see `tweaks_only ` [was changed to 0 last week](https://github.com/setavenger/blindbit-oracle/commit/a1cff9f20642f9d7cb04482def87e694dcf23107), but it remained 1 here because the file is outside the project dir ¯\_(ツ)_/¯

**Comment by setavenger** [comment]
That explains a lot. I did change the defaults to avoid exactly this problem. The base assumption of users is that the core functionality works.
Try running it with `tweaks_only = 0`. It should work now.

Sorry for that inconvenience!

I'm currently breaking quite a few features due a bigger overhaul. Some endpoints will change in a coming change as well. I will do better with regard to announcing and highlighting those breaking changes. In general though running the latest versions of blindbit-oracle and blindbitd should work.

I believe it's a bit early to introduce versioning or releases just yet due to these changes that frequently happen.

**Comment by ottosch** [comment]
Thanks, it worked.
